### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by Coding-Kiwi** [simonhuwiler/roccatvulcan#3]
Dude you are a freaking legend, you can delete this issue but I wanted to say thank you for this package somehow ❤️ 🎉

**Comment by simonhuwiler** [comment]
Ähm, thanks! What are you building?

**Comment by Coding-Kiwi** [comment]
@simonhuwiler Die Roccat Swarm Software ist sehr begrenzt, sie hat zwar den Effekt dass eine gedrückte Taste kurz aufleuchtet ("Verblassen") aber alle anderen Tasten sind dafür dann permanent dunkel. Allgemein fehlen stapelbare Effect-Layers, ich tobe mich grade ein wenig aus, dank deinem tollen package :)

**Comment by Coding-Kiwi** [comment]
ich meine wer wollte nicht schon immer mal Minecraft auf der Tastatur spielen
https://imgur.com/a/sMKAN3t

**Comment by simonhuwiler** [comment]
Hammer! Halt mich auf dem laufenden :-)
