### ISSUE TITLE
What is the recommended nodejs version?

### ISSUE THREAD

**Issue by erockce** [simonhuwiler/roccatvulcan#6]
Hi...I'm _really_ new to `nodejs` but have an IT and Software Development background.

I just purchased the Roccat Vulcan 120 and trying some of the open-source projects that work with it since my primary platform is Linux.

My question is: What version of `nodejs` should be used for this project and your other programs?

I am currently using NodeJS 12 LTS, but I'm having trouble just running the example code on the main page after I made a copy of the `de-de` layout to start the creation of `en-us`.  After moving the file into the `src` directory then it failed finding `grid.js`.  So I reverted back to `de-de` just so I could get going.

I get further but am receiving the a `UnhandledPromiseRejectionWarning` when I run the file:

```
$ node my-roccat-vulkan.js 
Initialize Vulcan
Roccat Server Ready
Keyboard is ready!
(node:13673) UnhandledPromiseRejectionWarning: ReferenceError: raise is not defined
    at Object.module.exports.sendColorsToKeyboard (/home/erockce/Development/nodejs/node_modules/roccatvulcan/src/controller.js:21:7)
    at RoccatVulkan.render (/home/erockce/Development/nodejs/node_modules/roccatvulcan/src/index.js:185:16)
    at Object.ready (/home/erockce/Development/GitHub/roccatvulcan/src/my-roccat-vulkan.js:14:14)
    at /home/erockce/Development/nodejs/node_modules/roccatvulcan/src/index.js:115:17
(node:13673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So then I added the recommended "`--unhandled-rejections=strict`". And get a bit further and with a different error.  The lights do get changed to _BRIGHT_ yellow. However then something strange happens where the FN+[F1-F4] doesn't work and the brightness control does not let me change the brightness back up from all the way off (and I did press the `FX` button first).

Unplugging and then plugging back in reset the keyboard and it returned back to the profile on FN-F3.

This keyboard is brand new from my local electronics store and I have not used the Swarm software (I don't know yet if it will work from a Windows 10 virtual machine) yet.

```
$ node --unhandled-rejections=strict my-roccat-vulkan.js
Initialize Vulcan
Roccat Server Ready
Keyboard is ready!
/home/erockce/Development/nodejs/node_modules/roccatvulcan/src/controller.js:21
      raise("Could not send data")
      ^
ReferenceError: raise is not defined
    at Object.module.exports.sendColorsToKeyboard (/home/erockce/Development/nodejs/node_modules/roccatvulcan/src/controller.js:21:7)
    at RoccatVulkan.render (/home/erockce/Development/nodejs/node_modules/roccatvulcan/src/index.js:185:16)
    at Object.ready (/home/erockce/Development/GitHub/simonhuwiler/roccatvulcan/src/my-roccat-vulkan.js:14:14)
    at /home/erockce/Development/nodejs/node_modules/roccatvulcan/src/index.js:115:17
```

Sorry this changed from a question to a possible bug.

This is my first RGB _and_ mechanical keyboard.  I am so very grateful to see people like you working on a open-source user-space applications to interact with these RGB keyboards!

**Comment by erockce** [comment]
I wanted to report that I updated to the latest available firmware at the time of this writing using a Windows 10 guest through VirtualBox.

Here are my Roccat software and firmware versions:
```
Roccat Swarm Version: v1.9368
Roccat Driver Version: v1.36
Roccat Vulcan AIMO 120, Firmware Version: v1.0029
```

Additional information:
```
[ 1159.165357] input: ROCCAT ROCCAT Vulcan AIMO as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/0003:1E7D:3098.0007/input/input20
[ 1159.224438] hid-generic 0003:1E7D:3098.0007: input,hidraw0: USB HID v1.11 Keyboard [ROCCAT ROCCAT Vulcan AIMO] on usb-0000:00:14.0-1/input0
[ 1159.225781] input: ROCCAT ROCCAT Vulcan AIMO Mouse as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.1/0003:1E7D:3098.0008/input/input21
[ 1159.284181] input: ROCCAT ROCCAT Vulcan AIMO Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.1/0003:1E7D:3098.0008/input/input22
[ 1159.284257] input: ROCCAT ROCCAT Vulcan AIMO System Control as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.1/0003:1E7D:3098.0008/input/input23
[ 1159.284425] hid-generic 0003:1E7D:3098.0008: input,hiddev0,hidraw1: USB HID v1.11 Mouse [ROCCAT ROCCAT Vulcan AIMO] on usb-0000:00:14.0-1/input1
[ 1159.287780] input: ROCCAT ROCCAT Vulcan AIMO as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.2/0003:1E7D:3098.0009/input/input25
[ 1159.344151] hid-generic 0003:1E7D:3098.0009: input,hidraw2: USB HID v1.11 Keypad [ROCCAT ROCCAT Vulcan AIMO] on usb-0000:00:14.0-1/input2
[ 1159.344604] input: ROCCAT ROCCAT Vulcan AIMO as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.3/0003:1E7D:3098.000A/input/input26
[ 1159.404426] hid-generic 0003:1E7D:3098.000A: input,hidraw3: USB HID v1.11 Device [ROCCAT ROCCAT Vulcan AIMO] on usb-0000:00:14.0-1/input3
```

```
erockce@nuc:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

Even having the keyboard at the latest firmware still yields the same error provided from my previous comment.

**Comment by simonhuwiler** [comment]
Hi Erockce
Thanks for your request. I am currently quite busy, but I will come back to you later!
Thanks!

**Comment by simonhuwiler** [comment]
Come back later... now its two years later... you probably dont use it anymore, but anyways: Published a new version, it should run now with the newest node version.
