### ISSUE TITLE
Project made with API

### ISSUE THREAD

**Issue by KiaraHD** [simonhuwiler/roccatvulcan#9]
Hey, i see you wrote in your *README* to contact you to be listed under `Projects made with this library`.

I made a snake game that you can play on a Roccat Vulcan: [Snake Vulcan](https://github.com/kiarahd/snake-vulcan).

It would be nice if would get added there :D

I could make a PR if needed. Let me know!

greetings 
Kiara

**Comment by simonhuwiler** [comment]
Hi Kiara

Congrats! Had to play it immediately!
It's now listed in the readme.

Grüsse nach Österreich!

Simon
